name: paystack_flutterwave_url
description: "A Flutter package for Paystack and Flutterwave checkout url payment."
version: 0.0.3
homepage: "https://github.com/Maxzeno/paystack_flutterwave_url"
repository: https://github.com/Maxzeno/paystack_flutterwave_url
issue_tracker: https://github.com/Maxzeno/paystack_flutterwave_url/issues

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  # webview_flutter: ^4.8.0
  flutter_inappwebview: ^6.1.5
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

platforms:
  android:
  ios:
  web:
