name: paystack_flutterwave_url
description: "A new Flutter package project."
version: 0.0.1
homepage: "https://github.com/Maxzeno/paystack_flutterwave_url"

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.8.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
