name: paystack_flutterwave_url
description: "A Flutter package for Paystack and Flutterwave checkout url payment."
version: 1.3.0
homepage: "https://github.com/Maxzeno/paystack_flutterwave_url"
repository: https://github.com/Maxzeno/paystack_flutterwave_url
issue_tracker: https://github.com/Maxzeno/paystack_flutterwave_url/issues

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.12.0
  url_launcher: ^6.3.0
  http: ^1.3.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

platforms:
  android:
  ios:
  web:
